export { default as Header } from "./Header";
export { default as Home } from "./Home";
export { default as About } from "./About";
export { default as Work } from "./Work";
export { default as Skills } from "./Skills";
export { default as Copyright } from "./Copyright";
export { default as SocialMedia } from "./SocialMedia";
export { default as NavigationDots } from "./NavigationDots";
export { default as Footer } from "./Footer";
